openapi: 3.0.1
info:
  title: 百人牛牛
  description: 'Server spec for 百人牛牛 card game.'
  version: 1.0.0
servers:
- url: http://localhost:9000/api/v1
tags:
- name: room
  description: Room operations
- name: room chip
  description: Room chip operations
paths:
  /cards:
    get:
      tags:
      - card
      summary: Returns all cards info
      description: Returns cards
      operationId: /cards
      parameters:
      - $ref: '#/components/parameters/noCacheParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Card'
        500:
          $ref: '#/components/responses/500InternalServerError'
  /rooms:
    get:
      tags:
      - room
      summary: Returns all rooms info
      description: Returns rooms, room chips
      operationId: /rooms
      parameters:
      - $ref: '#/components/parameters/noCacheParam'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        500:
          $ref: '#/components/responses/500InternalServerError'

components:
  schemas:
    Card:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Card id
          example: 1
        name:
          type: string
          description: Card name
          example: "J_2 means Jack Club"
        image_url:
          type: string
          description: Url of card image
          example: 'Cards/CCard_Jclub_result'
        points:
          type: integer
          description: Point of card. J, Q, K has 10 points
          example: 10
        suit:
          type: integer
          description: What suit does the card belongs to. Diamond 1, Club 2, Heart 3, Club 4
          example: 2
        rank:
          type: integer
          description: Rank of card
          example: 11
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Room id
          example: 1
        name:
          type: string
          description: Room name,
          example: "Beginner Room"
        room_chips:
          type: array
          items:
            $ref: '#/components/schemas/RoomChip'
    RoomChip:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Room chip id
          example: 2
        image_url:
          type: string
          description: Url of chip image,
          example: "Chips/chip_20_blue_result"
        value:
          type: integer
          format: int64
          description: Value of the chip,
          example: 20

  parameters:
    noCacheParam:
      name: no_cache
      in: query
      description: Whether to use cached data
      example: 1
      required: false
      schema:
        type: integer
        enum: [0, 1]
  responses:
    500InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              err_code:
                type: integer
                format: int
                description: Error code
                example: 500
              message:
                type: string
                description: Description of the error
                example: "Server encountered an error"
